// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sfs.metahive.model;

import java.lang.String;

privileged aspect Record_Roo_ToString {
    
    public String Record.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("RecordId: ").append(getRecordId());
        return sb.toString();
    }
    
}
