// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.triptech.metahive.model;

import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import net.triptech.metahive.model.ConditionOfUse;

import org.springframework.stereotype.Component;

privileged aspect ConditionOfUseDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ConditionOfUseDataOnDemand: @Component;
    
    private Random ConditionOfUseDataOnDemand.rnd = new SecureRandom();
    
    private List<ConditionOfUse> ConditionOfUseDataOnDemand.data;
    
    public ConditionOfUse ConditionOfUseDataOnDemand.getNewTransientConditionOfUse(int index) {
        ConditionOfUse obj = new ConditionOfUse();
        setDetails(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void ConditionOfUseDataOnDemand.setDetails(ConditionOfUse obj, int index) {
        String details = "details_" + index;
        obj.setDetails(details);
    }
    
    public void ConditionOfUseDataOnDemand.setName(ConditionOfUse obj, int index) {
        String name = "name_" + index;
        if (name.length() > 100) {
            name = new Random().nextInt(10) + name.substring(1, 100);
        }
        obj.setName(name);
    }
    
    public ConditionOfUse ConditionOfUseDataOnDemand.getSpecificConditionOfUse(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ConditionOfUse obj = data.get(index);
        return ConditionOfUse.findConditionOfUse(obj.getId());
    }
    
    public ConditionOfUse ConditionOfUseDataOnDemand.getRandomConditionOfUse() {
        init();
        ConditionOfUse obj = data.get(rnd.nextInt(data.size()));
        return ConditionOfUse.findConditionOfUse(obj.getId());
    }
    
    public boolean ConditionOfUseDataOnDemand.modifyConditionOfUse(ConditionOfUse obj) {
        return false;
    }
    
    public void ConditionOfUseDataOnDemand.init() {
        data = ConditionOfUse.findConditionOfUseEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ConditionOfUse' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<net.triptech.metahive.model.ConditionOfUse>();
        for (int i = 0; i < 10; i++) {
            ConditionOfUse obj = getNewTransientConditionOfUse(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
