// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.triptech.metahive.model;

import java.util.List;
import net.triptech.metahive.model.Definition;
import net.triptech.metahive.model.DefinitionDataOnDemand;
import net.triptech.metahive.model.DefinitionIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DefinitionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DefinitionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DefinitionIntegrationTest: @Transactional;
    
    @Autowired
    private DefinitionDataOnDemand DefinitionIntegrationTest.dod;
    
    @Test
    public void DefinitionIntegrationTest.testCountDefinitions() {
        Assert.assertNotNull("Data on demand for 'Definition' failed to initialize correctly", dod.getRandomDefinition());
        long count = Definition.countDefinitions();
        Assert.assertTrue("Counter for 'Definition' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DefinitionIntegrationTest.testFindDefinition() {
        Definition obj = dod.getRandomDefinition();
        Assert.assertNotNull("Data on demand for 'Definition' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Definition' failed to provide an identifier", id);
        obj = Definition.findDefinition(id);
        Assert.assertNotNull("Find method for 'Definition' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Definition' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DefinitionIntegrationTest.testFindAllDefinitions() {
        Assert.assertNotNull("Data on demand for 'Definition' failed to initialize correctly", dod.getRandomDefinition());
        long count = Definition.countDefinitions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Definition', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Definition> result = Definition.findAllDefinitions();
        Assert.assertNotNull("Find all method for 'Definition' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Definition' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DefinitionIntegrationTest.testFindDefinitionEntries() {
        Assert.assertNotNull("Data on demand for 'Definition' failed to initialize correctly", dod.getRandomDefinition());
        long count = Definition.countDefinitions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Definition> result = Definition.findDefinitionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Definition' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Definition' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DefinitionIntegrationTest.testFlush() {
        Definition obj = dod.getRandomDefinition();
        Assert.assertNotNull("Data on demand for 'Definition' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Definition' failed to provide an identifier", id);
        obj = Definition.findDefinition(id);
        Assert.assertNotNull("Find method for 'Definition' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDefinition(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Definition' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DefinitionIntegrationTest.testMergeUpdate() {
        Definition obj = dod.getRandomDefinition();
        Assert.assertNotNull("Data on demand for 'Definition' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Definition' failed to provide an identifier", id);
        obj = Definition.findDefinition(id);
        boolean modified =  dod.modifyDefinition(obj);
        Integer currentVersion = obj.getVersion();
        Definition merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Definition' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DefinitionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Definition' failed to initialize correctly", dod.getRandomDefinition());
        Definition obj = dod.getNewTransientDefinition(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Definition' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Definition' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Definition' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DefinitionIntegrationTest.testRemove() {
        Definition obj = dod.getRandomDefinition();
        Assert.assertNotNull("Data on demand for 'Definition' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Definition' failed to provide an identifier", id);
        obj = Definition.findDefinition(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Definition' with identifier '" + id + "'", Definition.findDefinition(id));
    }
    
}
