// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.triptech.metahive.model;

import java.util.List;
import net.triptech.metahive.model.Description;
import net.triptech.metahive.model.DescriptionDataOnDemand;
import net.triptech.metahive.model.DescriptionIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DescriptionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DescriptionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DescriptionIntegrationTest: @Transactional;
    
    @Autowired
    private DescriptionDataOnDemand DescriptionIntegrationTest.dod;
    
    @Test
    public void DescriptionIntegrationTest.testCountDescriptions() {
        Assert.assertNotNull("Data on demand for 'Description' failed to initialize correctly", dod.getRandomDescription());
        long count = Description.countDescriptions();
        Assert.assertTrue("Counter for 'Description' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DescriptionIntegrationTest.testFindDescription() {
        Description obj = dod.getRandomDescription();
        Assert.assertNotNull("Data on demand for 'Description' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Description' failed to provide an identifier", id);
        obj = Description.findDescription(id);
        Assert.assertNotNull("Find method for 'Description' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Description' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DescriptionIntegrationTest.testFindAllDescriptions() {
        Assert.assertNotNull("Data on demand for 'Description' failed to initialize correctly", dod.getRandomDescription());
        long count = Description.countDescriptions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Description', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Description> result = Description.findAllDescriptions();
        Assert.assertNotNull("Find all method for 'Description' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Description' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DescriptionIntegrationTest.testFindDescriptionEntries() {
        Assert.assertNotNull("Data on demand for 'Description' failed to initialize correctly", dod.getRandomDescription());
        long count = Description.countDescriptions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Description> result = Description.findDescriptionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Description' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Description' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DescriptionIntegrationTest.testFlush() {
        Description obj = dod.getRandomDescription();
        Assert.assertNotNull("Data on demand for 'Description' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Description' failed to provide an identifier", id);
        obj = Description.findDescription(id);
        Assert.assertNotNull("Find method for 'Description' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDescription(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Description' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DescriptionIntegrationTest.testMergeUpdate() {
        Description obj = dod.getRandomDescription();
        Assert.assertNotNull("Data on demand for 'Description' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Description' failed to provide an identifier", id);
        obj = Description.findDescription(id);
        boolean modified =  dod.modifyDescription(obj);
        Integer currentVersion = obj.getVersion();
        Description merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Description' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DescriptionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Description' failed to initialize correctly", dod.getRandomDescription());
        Description obj = dod.getNewTransientDescription(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Description' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Description' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Description' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DescriptionIntegrationTest.testRemove() {
        Description obj = dod.getRandomDescription();
        Assert.assertNotNull("Data on demand for 'Description' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Description' failed to provide an identifier", id);
        obj = Description.findDescription(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Description' with identifier '" + id + "'", Description.findDescription(id));
    }
    
}
