// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.triptech.metahive.model;

import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.triptech.metahive.model.Record;
import org.springframework.stereotype.Component;

privileged aspect RecordOnDemand_Roo_DataOnDemand {
    
    declare @type: RecordOnDemand: @Component;
    
    private Random RecordOnDemand.rnd = new SecureRandom();
    
    private List<Record> RecordOnDemand.data;
    
    public Record RecordOnDemand.getNewTransientRecord(int index) {
        Record obj = new Record();
        setRecordId(obj, index);
        return obj;
    }
    
    public void RecordOnDemand.setRecordId(Record obj, int index) {
        String recordId = "recordId_" + index;
        if (recordId.length() > 255) {
            recordId = new Random().nextInt(10) + recordId.substring(1, 255);
        }
        obj.setRecordId(recordId);
    }
    
    public Record RecordOnDemand.getSpecificRecord(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Record obj = data.get(index);
        return Record.findRecord(obj.getId());
    }
    
    public Record RecordOnDemand.getRandomRecord() {
        init();
        Record obj = data.get(rnd.nextInt(data.size()));
        return Record.findRecord(obj.getId());
    }
    
    public boolean RecordOnDemand.modifyRecord(Record obj) {
        return false;
    }
    
    public void RecordOnDemand.init() {
        data = Record.findRecordEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Record' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<net.triptech.metahive.model.Record>();
        for (int i = 0; i < 10; i++) {
            Record obj = getNewTransientRecord(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
