// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.triptech.metahive.model;

import java.util.List;
import net.triptech.metahive.model.Record;
import net.triptech.metahive.model.RecordDataOnDemand;
import net.triptech.metahive.model.RecordIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RecordIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RecordIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RecordIntegrationTest: @Transactional;
    
    @Autowired
    private RecordDataOnDemand RecordIntegrationTest.dod;
    
    @Test
    public void RecordIntegrationTest.testCountRecords() {
        Assert.assertNotNull("Data on demand for 'Record' failed to initialize correctly", dod.getRandomRecord());
        long count = Record.countRecords();
        Assert.assertTrue("Counter for 'Record' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RecordIntegrationTest.testFindRecord() {
        Record obj = dod.getRandomRecord();
        Assert.assertNotNull("Data on demand for 'Record' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Record' failed to provide an identifier", id);
        obj = Record.findRecord(id);
        Assert.assertNotNull("Find method for 'Record' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Record' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RecordIntegrationTest.testFindAllRecords() {
        Assert.assertNotNull("Data on demand for 'Record' failed to initialize correctly", dod.getRandomRecord());
        long count = Record.countRecords();
        Assert.assertTrue("Too expensive to perform a find all test for 'Record', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Record> result = Record.findAllRecords();
        Assert.assertNotNull("Find all method for 'Record' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Record' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RecordIntegrationTest.testFindRecordEntries() {
        Assert.assertNotNull("Data on demand for 'Record' failed to initialize correctly", dod.getRandomRecord());
        long count = Record.countRecords();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Record> result = Record.findRecordEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Record' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Record' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RecordIntegrationTest.testFlush() {
        Record obj = dod.getRandomRecord();
        Assert.assertNotNull("Data on demand for 'Record' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Record' failed to provide an identifier", id);
        obj = Record.findRecord(id);
        Assert.assertNotNull("Find method for 'Record' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRecord(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Record' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RecordIntegrationTest.testMergeUpdate() {
        Record obj = dod.getRandomRecord();
        Assert.assertNotNull("Data on demand for 'Record' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Record' failed to provide an identifier", id);
        obj = Record.findRecord(id);
        boolean modified =  dod.modifyRecord(obj);
        Integer currentVersion = obj.getVersion();
        Record merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Record' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RecordIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Record' failed to initialize correctly", dod.getRandomRecord());
        Record obj = dod.getNewTransientRecord(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Record' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Record' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Record' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RecordIntegrationTest.testRemove() {
        Record obj = dod.getRandomRecord();
        Assert.assertNotNull("Data on demand for 'Record' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Record' failed to provide an identifier", id);
        obj = Record.findRecord(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Record' with identifier '" + id + "'", Record.findRecord(id));
    }
    
}
