// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sfs.metahive.model;

import com.sfs.metahive.model.DataType;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect DataTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DataTypeDataOnDemand: @Component;
    
    private Random DataTypeDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<DataType> DataTypeDataOnDemand.data;
    
    public DataType DataTypeDataOnDemand.getNewTransientDataType(int index) {
        com.sfs.metahive.model.DataType obj = new com.sfs.metahive.model.DataType();
        setName(obj, index);
        return obj;
    }
    
    private void DataTypeDataOnDemand.setName(DataType obj, int index) {
        java.lang.String name = "name_" + index;
        if (name.length() > 100) {
            name = name.substring(0, 100);
        }
        obj.setName(name);
    }
    
    public DataType DataTypeDataOnDemand.getSpecificDataType(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        DataType obj = data.get(index);
        return DataType.findDataType(obj.getId());
    }
    
    public DataType DataTypeDataOnDemand.getRandomDataType() {
        init();
        DataType obj = data.get(rnd.nextInt(data.size()));
        return DataType.findDataType(obj.getId());
    }
    
    public boolean DataTypeDataOnDemand.modifyDataType(DataType obj) {
        return false;
    }
    
    public void DataTypeDataOnDemand.init() {
        data = com.sfs.metahive.model.DataType.findDataTypeEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'DataType' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.sfs.metahive.model.DataType>();
        for (int i = 0; i < 10; i++) {
            com.sfs.metahive.model.DataType obj = getNewTransientDataType(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
