// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sfs.metahive.model;

import com.sfs.metahive.model.ConditionOfUseDataOnDemand;
import com.sfs.metahive.model.DataSource;
import com.sfs.metahive.model.DefinitionDataOnDemand;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DataSourceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DataSourceDataOnDemand: @Component;
    
    private Random DataSourceDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<DataSource> DataSourceDataOnDemand.data;
    
    @Autowired
    private ConditionOfUseDataOnDemand DataSourceDataOnDemand.conditionOfUseDataOnDemand;
    
    @Autowired
    private DefinitionDataOnDemand DataSourceDataOnDemand.definitionDataOnDemand;
    
    public DataSource DataSourceDataOnDemand.getNewTransientDataSource(int index) {
        com.sfs.metahive.model.DataSource obj = new com.sfs.metahive.model.DataSource();
        setConditionOfUse(obj, index);
        setDefinition(obj, index);
        return obj;
    }
    
    private void DataSourceDataOnDemand.setConditionOfUse(DataSource obj, int index) {
        com.sfs.metahive.model.ConditionOfUse conditionOfUse = conditionOfUseDataOnDemand.getRandomConditionOfUse();
        obj.setConditionOfUse(conditionOfUse);
    }
    
    private void DataSourceDataOnDemand.setDefinition(DataSource obj, int index) {
        com.sfs.metahive.model.Definition definition = definitionDataOnDemand.getRandomDefinition();
        obj.setDefinition(definition);
    }
    
    public DataSource DataSourceDataOnDemand.getSpecificDataSource(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        DataSource obj = data.get(index);
        return DataSource.findDataSource(obj.getId());
    }
    
    public DataSource DataSourceDataOnDemand.getRandomDataSource() {
        init();
        DataSource obj = data.get(rnd.nextInt(data.size()));
        return DataSource.findDataSource(obj.getId());
    }
    
    public boolean DataSourceDataOnDemand.modifyDataSource(DataSource obj) {
        return false;
    }
    
    public void DataSourceDataOnDemand.init() {
        data = com.sfs.metahive.model.DataSource.findDataSourceEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'DataSource' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.sfs.metahive.model.DataSource>();
        for (int i = 0; i < 10; i++) {
            com.sfs.metahive.model.DataSource obj = getNewTransientDataSource(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
