// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sfs.metahive.model;

import com.sfs.metahive.model.DataType;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect DataTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DataTypeDataOnDemand: @Component;
    
    private Random DataTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<DataType> DataTypeDataOnDemand.data;
    
    public DataType DataTypeDataOnDemand.getNewTransientDataType(int index) {
        DataType obj = new DataType();
        setName(obj, index);
        return obj;
    }
    
    public void DataTypeDataOnDemand.setName(DataType obj, int index) {
        String name = "name_" + index;
        if (name.length() > 100) {
            name = new Random().nextInt(10) + name.substring(1, 100);
        }
        obj.setName(name);
    }
    
    public DataType DataTypeDataOnDemand.getSpecificDataType(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        DataType obj = data.get(index);
        return DataType.findDataType(obj.getId());
    }
    
    public DataType DataTypeDataOnDemand.getRandomDataType() {
        init();
        DataType obj = data.get(rnd.nextInt(data.size()));
        return DataType.findDataType(obj.getId());
    }
    
    public boolean DataTypeDataOnDemand.modifyDataType(DataType obj) {
        return false;
    }
    
    public void DataTypeDataOnDemand.init() {
        data = DataType.findDataTypeEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'DataType' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.sfs.metahive.model.DataType>();
        for (int i = 0; i < 10; i++) {
            DataType obj = getNewTransientDataType(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
