// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sfs.metahive.model;

import com.sfs.metahive.model.Comment;
import com.sfs.metahive.model.ConditionOfUse;
import com.sfs.metahive.model.ConditionOfUseDataOnDemand;
import com.sfs.metahive.model.DataSource;
import com.sfs.metahive.model.Definition;
import com.sfs.metahive.model.DefinitionDataOnDemand;
import com.sfs.metahive.model.Organisation;
import com.sfs.metahive.model.OrganisationDataOnDemand;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DataSourceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DataSourceDataOnDemand: @Component;
    
    private Random DataSourceDataOnDemand.rnd = new SecureRandom();
    
    private List<DataSource> DataSourceDataOnDemand.data;
    
    @Autowired
    private ConditionOfUseDataOnDemand DataSourceDataOnDemand.conditionOfUseDataOnDemand;
    
    @Autowired
    private DefinitionDataOnDemand DataSourceDataOnDemand.definitionDataOnDemand;
    
    @Autowired
    private OrganisationDataOnDemand DataSourceDataOnDemand.organisationDataOnDemand;
    
    public DataSource DataSourceDataOnDemand.getNewTransientDataSource(int index) {
        DataSource obj = new DataSource();
        setComment(obj, index);
        setConditionOfUse(obj, index);
        setDefinition(obj, index);
        setDetails(obj, index);
        setOrganisation(obj, index);
        return obj;
    }
    
    public void DataSourceDataOnDemand.setComment(DataSource obj, int index) {
        Comment comment = null;
        obj.setComment(comment);
    }
    
    public void DataSourceDataOnDemand.setConditionOfUse(DataSource obj, int index) {
        ConditionOfUse conditionOfUse = conditionOfUseDataOnDemand.getRandomConditionOfUse();
        obj.setConditionOfUse(conditionOfUse);
    }
    
    public void DataSourceDataOnDemand.setDefinition(DataSource obj, int index) {
        Definition definition = definitionDataOnDemand.getRandomDefinition();
        obj.setDefinition(definition);
    }
    
    public void DataSourceDataOnDemand.setDetails(DataSource obj, int index) {
        String details = "details_" + index;
        obj.setDetails(details);
    }
    
    public void DataSourceDataOnDemand.setOrganisation(DataSource obj, int index) {
        Organisation organisation = organisationDataOnDemand.getRandomOrganisation();
        obj.setOrganisation(organisation);
    }
    
    public DataSource DataSourceDataOnDemand.getSpecificDataSource(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        DataSource obj = data.get(index);
        return DataSource.findDataSource(obj.getId());
    }
    
    public DataSource DataSourceDataOnDemand.getRandomDataSource() {
        init();
        DataSource obj = data.get(rnd.nextInt(data.size()));
        return DataSource.findDataSource(obj.getId());
    }
    
    public boolean DataSourceDataOnDemand.modifyDataSource(DataSource obj) {
        return false;
    }
    
    public void DataSourceDataOnDemand.init() {
        data = DataSource.findDataSourceEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'DataSource' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.sfs.metahive.model.DataSource>();
        for (int i = 0; i < 10; i++) {
            DataSource obj = getNewTransientDataSource(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
