// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sfs.metahive.model;

import com.sfs.metahive.model.DataSourceDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DataSourceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DataSourceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DataSourceIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: DataSourceIntegrationTest: @Transactional;
    
    @Autowired
    private DataSourceDataOnDemand DataSourceIntegrationTest.dod;
    
    @Test
    public void DataSourceIntegrationTest.testCountDataSources() {
        org.junit.Assert.assertNotNull("Data on demand for 'DataSource' failed to initialize correctly", dod.getRandomDataSource());
        long count = com.sfs.metahive.model.DataSource.countDataSources();
        org.junit.Assert.assertTrue("Counter for 'DataSource' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DataSourceIntegrationTest.testFindDataSource() {
        com.sfs.metahive.model.DataSource obj = dod.getRandomDataSource();
        org.junit.Assert.assertNotNull("Data on demand for 'DataSource' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DataSource' failed to provide an identifier", id);
        obj = com.sfs.metahive.model.DataSource.findDataSource(id);
        org.junit.Assert.assertNotNull("Find method for 'DataSource' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'DataSource' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DataSourceIntegrationTest.testFindAllDataSources() {
        org.junit.Assert.assertNotNull("Data on demand for 'DataSource' failed to initialize correctly", dod.getRandomDataSource());
        long count = com.sfs.metahive.model.DataSource.countDataSources();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'DataSource', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.sfs.metahive.model.DataSource> result = com.sfs.metahive.model.DataSource.findAllDataSources();
        org.junit.Assert.assertNotNull("Find all method for 'DataSource' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'DataSource' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DataSourceIntegrationTest.testFindDataSourceEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'DataSource' failed to initialize correctly", dod.getRandomDataSource());
        long count = com.sfs.metahive.model.DataSource.countDataSources();
        if (count > 20) count = 20;
        java.util.List<com.sfs.metahive.model.DataSource> result = com.sfs.metahive.model.DataSource.findDataSourceEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'DataSource' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'DataSource' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DataSourceIntegrationTest.testFlush() {
        com.sfs.metahive.model.DataSource obj = dod.getRandomDataSource();
        org.junit.Assert.assertNotNull("Data on demand for 'DataSource' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DataSource' failed to provide an identifier", id);
        obj = com.sfs.metahive.model.DataSource.findDataSource(id);
        org.junit.Assert.assertNotNull("Find method for 'DataSource' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDataSource(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'DataSource' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DataSourceIntegrationTest.testMerge() {
        com.sfs.metahive.model.DataSource obj = dod.getRandomDataSource();
        org.junit.Assert.assertNotNull("Data on demand for 'DataSource' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DataSource' failed to provide an identifier", id);
        obj = com.sfs.metahive.model.DataSource.findDataSource(id);
        boolean modified =  dod.modifyDataSource(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.sfs.metahive.model.DataSource merged = (com.sfs.metahive.model.DataSource) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'DataSource' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DataSourceIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'DataSource' failed to initialize correctly", dod.getRandomDataSource());
        com.sfs.metahive.model.DataSource obj = dod.getNewTransientDataSource(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'DataSource' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'DataSource' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'DataSource' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DataSourceIntegrationTest.testRemove() {
        com.sfs.metahive.model.DataSource obj = dod.getRandomDataSource();
        org.junit.Assert.assertNotNull("Data on demand for 'DataSource' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DataSource' failed to provide an identifier", id);
        obj = com.sfs.metahive.model.DataSource.findDataSource(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'DataSource' with identifier '" + id + "'", com.sfs.metahive.model.DataSource.findDataSource(id));
    }
    
}
