// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sfs.metahive.model;

import com.sfs.metahive.model.Category;
import com.sfs.metahive.model.CategoryDataOnDemand;
import com.sfs.metahive.model.DataType;
import com.sfs.metahive.model.Definition;
import com.sfs.metahive.model.RecordType;
import com.sfs.metahive.model.RecordTypeDataOnDemand;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DefinitionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DefinitionDataOnDemand: @Component;
    
    private Random DefinitionDataOnDemand.rnd = new SecureRandom();
    
    private List<Definition> DefinitionDataOnDemand.data;
    
    @Autowired
    private CategoryDataOnDemand DefinitionDataOnDemand.categoryDataOnDemand;
    
    @Autowired
    private RecordTypeDataOnDemand DefinitionDataOnDemand.recordTypeDataOnDemand;
    
    public Definition DefinitionDataOnDemand.getNewTransientDefinition(int index) {
        Definition obj = new Definition();
        setCategory(obj, index);
        setDataType(obj, index);
        setName(obj, index);
        setRecordType(obj, index);
        setUnitOfMeasure(obj, index);
        return obj;
    }
    
    public void DefinitionDataOnDemand.setCategory(Definition obj, int index) {
        Category category = categoryDataOnDemand.getRandomCategory();
        obj.setCategory(category);
    }
    
    public void DefinitionDataOnDemand.setDataType(Definition obj, int index) {
        DataType dataType = DataType.class.getEnumConstants()[0];
        obj.setDataType(dataType);
    }
    
    public void DefinitionDataOnDemand.setName(Definition obj, int index) {
        String name = "name_" + index;
        if (name.length() > 100) {
            name = new Random().nextInt(10) + name.substring(1, 100);
        }
        obj.setName(name);
    }
    
    public void DefinitionDataOnDemand.setRecordType(Definition obj, int index) {
        RecordType recordType = recordTypeDataOnDemand.getRandomRecordType();
        obj.setRecordType(recordType);
    }
    
    public void DefinitionDataOnDemand.setUnitOfMeasure(Definition obj, int index) {
        String unitOfMeasure = "unitOfMeasure_" + index;
        obj.setUnitOfMeasure(unitOfMeasure);
    }
    
    public Definition DefinitionDataOnDemand.getSpecificDefinition(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Definition obj = data.get(index);
        return Definition.findDefinition(obj.getId());
    }
    
    public Definition DefinitionDataOnDemand.getRandomDefinition() {
        init();
        Definition obj = data.get(rnd.nextInt(data.size()));
        return Definition.findDefinition(obj.getId());
    }
    
    public boolean DefinitionDataOnDemand.modifyDefinition(Definition obj) {
        return false;
    }
    
    public void DefinitionDataOnDemand.init() {
        data = Definition.findDefinitionEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Definition' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.sfs.metahive.model.Definition>();
        for (int i = 0; i < 10; i++) {
            Definition obj = getNewTransientDefinition(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
