// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sfs.metahive.model;

import com.sfs.metahive.model.DefinitionDataOnDemand;
import com.sfs.metahive.model.Description;
import com.sfs.metahive.model.PersonDataOnDemand;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DescriptionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DescriptionDataOnDemand: @Component;
    
    private Random DescriptionDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Description> DescriptionDataOnDemand.data;
    
    @Autowired
    private DefinitionDataOnDemand DescriptionDataOnDemand.definitionDataOnDemand;
    
    @Autowired
    private PersonDataOnDemand DescriptionDataOnDemand.personDataOnDemand;
    
    public Description DescriptionDataOnDemand.getNewTransientDescription(int index) {
        com.sfs.metahive.model.Description obj = new com.sfs.metahive.model.Description();
        setDefinition(obj, index);
        setDescription(obj, index);
        setExampleValues(obj, index);
        setPerson(obj, index);
        setCreated(obj, index);
        return obj;
    }
    
    private void DescriptionDataOnDemand.setDefinition(Description obj, int index) {
        com.sfs.metahive.model.Definition definition = definitionDataOnDemand.getRandomDefinition();
        obj.setDefinition(definition);
    }
    
    private void DescriptionDataOnDemand.setDescription(Description obj, int index) {
        java.lang.String description = "description_" + index;
        obj.setDescription(description);
    }
    
    private void DescriptionDataOnDemand.setExampleValues(Description obj, int index) {
        java.lang.String exampleValues = "exampleValues_" + index;
        obj.setExampleValues(exampleValues);
    }
    
    private void DescriptionDataOnDemand.setPerson(Description obj, int index) {
        com.sfs.metahive.model.Person person = personDataOnDemand.getRandomPerson();
        obj.setPerson(person);
    }
    
    private void DescriptionDataOnDemand.setCreated(Description obj, int index) {
        java.util.Date created = new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreated(created);
    }
    
    public Description DescriptionDataOnDemand.getSpecificDescription(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Description obj = data.get(index);
        return Description.findDescription(obj.getId());
    }
    
    public Description DescriptionDataOnDemand.getRandomDescription() {
        init();
        Description obj = data.get(rnd.nextInt(data.size()));
        return Description.findDescription(obj.getId());
    }
    
    public boolean DescriptionDataOnDemand.modifyDescription(Description obj) {
        return false;
    }
    
    public void DescriptionDataOnDemand.init() {
        data = com.sfs.metahive.model.Description.findDescriptionEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Description' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.sfs.metahive.model.Description>();
        for (int i = 0; i < 10; i++) {
            com.sfs.metahive.model.Description obj = getNewTransientDescription(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
