// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sfs.metahive.model;

import com.sfs.metahive.model.Organisation;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect OrganisationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OrganisationDataOnDemand: @Component;
    
    private Random OrganisationDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Organisation> OrganisationDataOnDemand.data;
    
    public Organisation OrganisationDataOnDemand.getNewTransientOrganisation(int index) {
        com.sfs.metahive.model.Organisation obj = new com.sfs.metahive.model.Organisation();
        setName(obj, index);
        return obj;
    }
    
    private void OrganisationDataOnDemand.setName(Organisation obj, int index) {
        java.lang.String name = "name_" + index;
        if (name.length() > 100) {
            name = name.substring(0, 100);
        }
        obj.setName(name);
    }
    
    public Organisation OrganisationDataOnDemand.getSpecificOrganisation(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Organisation obj = data.get(index);
        return Organisation.findOrganisation(obj.getId());
    }
    
    public Organisation OrganisationDataOnDemand.getRandomOrganisation() {
        init();
        Organisation obj = data.get(rnd.nextInt(data.size()));
        return Organisation.findOrganisation(obj.getId());
    }
    
    public boolean OrganisationDataOnDemand.modifyOrganisation(Organisation obj) {
        return false;
    }
    
    public void OrganisationDataOnDemand.init() {
        data = com.sfs.metahive.model.Organisation.findOrganisationEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Organisation' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.sfs.metahive.model.Organisation>();
        for (int i = 0; i < 10; i++) {
            com.sfs.metahive.model.Organisation obj = getNewTransientOrganisation(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
