// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sfs.metahive.model;

import com.sfs.metahive.model.OrganisationDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OrganisationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OrganisationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OrganisationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: OrganisationIntegrationTest: @Transactional;
    
    @Autowired
    private OrganisationDataOnDemand OrganisationIntegrationTest.dod;
    
    @Test
    public void OrganisationIntegrationTest.testCountOrganisations() {
        org.junit.Assert.assertNotNull("Data on demand for 'Organisation' failed to initialize correctly", dod.getRandomOrganisation());
        long count = com.sfs.metahive.model.Organisation.countOrganisations();
        org.junit.Assert.assertTrue("Counter for 'Organisation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OrganisationIntegrationTest.testFindOrganisation() {
        com.sfs.metahive.model.Organisation obj = dod.getRandomOrganisation();
        org.junit.Assert.assertNotNull("Data on demand for 'Organisation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Organisation' failed to provide an identifier", id);
        obj = com.sfs.metahive.model.Organisation.findOrganisation(id);
        org.junit.Assert.assertNotNull("Find method for 'Organisation' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Organisation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OrganisationIntegrationTest.testFindAllOrganisations() {
        org.junit.Assert.assertNotNull("Data on demand for 'Organisation' failed to initialize correctly", dod.getRandomOrganisation());
        long count = com.sfs.metahive.model.Organisation.countOrganisations();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Organisation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.sfs.metahive.model.Organisation> result = com.sfs.metahive.model.Organisation.findAllOrganisations();
        org.junit.Assert.assertNotNull("Find all method for 'Organisation' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Organisation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OrganisationIntegrationTest.testFindOrganisationEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Organisation' failed to initialize correctly", dod.getRandomOrganisation());
        long count = com.sfs.metahive.model.Organisation.countOrganisations();
        if (count > 20) count = 20;
        java.util.List<com.sfs.metahive.model.Organisation> result = com.sfs.metahive.model.Organisation.findOrganisationEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Organisation' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Organisation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OrganisationIntegrationTest.testFlush() {
        com.sfs.metahive.model.Organisation obj = dod.getRandomOrganisation();
        org.junit.Assert.assertNotNull("Data on demand for 'Organisation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Organisation' failed to provide an identifier", id);
        obj = com.sfs.metahive.model.Organisation.findOrganisation(id);
        org.junit.Assert.assertNotNull("Find method for 'Organisation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOrganisation(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Organisation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OrganisationIntegrationTest.testMerge() {
        com.sfs.metahive.model.Organisation obj = dod.getRandomOrganisation();
        org.junit.Assert.assertNotNull("Data on demand for 'Organisation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Organisation' failed to provide an identifier", id);
        obj = com.sfs.metahive.model.Organisation.findOrganisation(id);
        boolean modified =  dod.modifyOrganisation(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.sfs.metahive.model.Organisation merged = (com.sfs.metahive.model.Organisation) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Organisation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OrganisationIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Organisation' failed to initialize correctly", dod.getRandomOrganisation());
        com.sfs.metahive.model.Organisation obj = dod.getNewTransientOrganisation(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Organisation' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Organisation' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Organisation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OrganisationIntegrationTest.testRemove() {
        com.sfs.metahive.model.Organisation obj = dod.getRandomOrganisation();
        org.junit.Assert.assertNotNull("Data on demand for 'Organisation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Organisation' failed to provide an identifier", id);
        obj = com.sfs.metahive.model.Organisation.findOrganisation(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Organisation' with identifier '" + id + "'", com.sfs.metahive.model.Organisation.findOrganisation(id));
    }
    
}
