// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sfs.metahive.model;

import com.sfs.metahive.model.Person;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect PersonDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PersonDataOnDemand: @Component;
    
    private Random PersonDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Person> PersonDataOnDemand.data;
    
    public Person PersonDataOnDemand.getNewTransientPerson(int index) {
        com.sfs.metahive.model.Person obj = new com.sfs.metahive.model.Person();
        setOpenIdIdentifier(obj, index);
        setUserRole(obj, index);
        setUserStatus(obj, index);
        setFirstName(obj, index);
        setLastName(obj, index);
        setEmailAddress(obj, index);
        return obj;
    }
    
    private void PersonDataOnDemand.setOpenIdIdentifier(Person obj, int index) {
        java.lang.String openIdIdentifier = "openIdIdentifier_" + index;
        obj.setOpenIdIdentifier(openIdIdentifier);
    }
    
    private void PersonDataOnDemand.setUserRole(Person obj, int index) {
        com.sfs.metahive.model.UserRole userRole = com.sfs.metahive.model.UserRole.class.getEnumConstants()[0];
        obj.setUserRole(userRole);
    }
    
    private void PersonDataOnDemand.setUserStatus(Person obj, int index) {
        com.sfs.metahive.model.UserStatus userStatus = com.sfs.metahive.model.UserStatus.class.getEnumConstants()[0];
        obj.setUserStatus(userStatus);
    }
    
    private void PersonDataOnDemand.setFirstName(Person obj, int index) {
        java.lang.String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    private void PersonDataOnDemand.setLastName(Person obj, int index) {
        java.lang.String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
    private void PersonDataOnDemand.setEmailAddress(Person obj, int index) {
        java.lang.String emailAddress = "emailAddress_" + index;
        obj.setEmailAddress(emailAddress);
    }
    
    public Person PersonDataOnDemand.getSpecificPerson(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Person obj = data.get(index);
        return Person.findPerson(obj.getId());
    }
    
    public Person PersonDataOnDemand.getRandomPerson() {
        init();
        Person obj = data.get(rnd.nextInt(data.size()));
        return Person.findPerson(obj.getId());
    }
    
    public boolean PersonDataOnDemand.modifyPerson(Person obj) {
        return false;
    }
    
    public void PersonDataOnDemand.init() {
        data = com.sfs.metahive.model.Person.findPersonEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Person' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.sfs.metahive.model.Person>();
        for (int i = 0; i < 10; i++) {
            com.sfs.metahive.model.Person obj = getNewTransientPerson(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
