// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sfs.metahive.model;

import com.sfs.metahive.model.RecordTypeDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RecordTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RecordTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RecordTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RecordTypeIntegrationTest: @Transactional;
    
    @Autowired
    private RecordTypeDataOnDemand RecordTypeIntegrationTest.dod;
    
    @Test
    public void RecordTypeIntegrationTest.testCountRecordTypes() {
        org.junit.Assert.assertNotNull("Data on demand for 'RecordType' failed to initialize correctly", dod.getRandomRecordType());
        long count = com.sfs.metahive.model.RecordType.countRecordTypes();
        org.junit.Assert.assertTrue("Counter for 'RecordType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RecordTypeIntegrationTest.testFindRecordType() {
        com.sfs.metahive.model.RecordType obj = dod.getRandomRecordType();
        org.junit.Assert.assertNotNull("Data on demand for 'RecordType' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RecordType' failed to provide an identifier", id);
        obj = com.sfs.metahive.model.RecordType.findRecordType(id);
        org.junit.Assert.assertNotNull("Find method for 'RecordType' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'RecordType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RecordTypeIntegrationTest.testFindAllRecordTypes() {
        org.junit.Assert.assertNotNull("Data on demand for 'RecordType' failed to initialize correctly", dod.getRandomRecordType());
        long count = com.sfs.metahive.model.RecordType.countRecordTypes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'RecordType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.sfs.metahive.model.RecordType> result = com.sfs.metahive.model.RecordType.findAllRecordTypes();
        org.junit.Assert.assertNotNull("Find all method for 'RecordType' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'RecordType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RecordTypeIntegrationTest.testFindRecordTypeEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'RecordType' failed to initialize correctly", dod.getRandomRecordType());
        long count = com.sfs.metahive.model.RecordType.countRecordTypes();
        if (count > 20) count = 20;
        java.util.List<com.sfs.metahive.model.RecordType> result = com.sfs.metahive.model.RecordType.findRecordTypeEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'RecordType' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'RecordType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RecordTypeIntegrationTest.testFlush() {
        com.sfs.metahive.model.RecordType obj = dod.getRandomRecordType();
        org.junit.Assert.assertNotNull("Data on demand for 'RecordType' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RecordType' failed to provide an identifier", id);
        obj = com.sfs.metahive.model.RecordType.findRecordType(id);
        org.junit.Assert.assertNotNull("Find method for 'RecordType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRecordType(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'RecordType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RecordTypeIntegrationTest.testMerge() {
        com.sfs.metahive.model.RecordType obj = dod.getRandomRecordType();
        org.junit.Assert.assertNotNull("Data on demand for 'RecordType' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RecordType' failed to provide an identifier", id);
        obj = com.sfs.metahive.model.RecordType.findRecordType(id);
        boolean modified =  dod.modifyRecordType(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.sfs.metahive.model.RecordType merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'RecordType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RecordTypeIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'RecordType' failed to initialize correctly", dod.getRandomRecordType());
        com.sfs.metahive.model.RecordType obj = dod.getNewTransientRecordType(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'RecordType' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'RecordType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'RecordType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RecordTypeIntegrationTest.testRemove() {
        com.sfs.metahive.model.RecordType obj = dod.getRandomRecordType();
        org.junit.Assert.assertNotNull("Data on demand for 'RecordType' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RecordType' failed to provide an identifier", id);
        obj = com.sfs.metahive.model.RecordType.findRecordType(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'RecordType' with identifier '" + id + "'", com.sfs.metahive.model.RecordType.findRecordType(id));
    }
    
}
