// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sfs.metahive.web.model;

import java.lang.String;

privileged aspect BaseFilter_Roo_JavaBean {

    public String BaseFilter.getEncoding() {
        return this.encoding;
    }

    public void BaseFilter.setEncoding(String encoding) {
        this.encoding = encoding;
    }

}
