// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sfs.metahive.web.model;

import java.lang.String;

privileged aspect RecordFilter_Roo_JavaBean {

    public String RecordFilter.getRecordId() {
        return this.recordId;
    }

    public void RecordFilter.setRecordId(String recordId) {
        this.recordId = recordId;
    }

}
