// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.triptech.metahive.model;

import net.triptech.metahive.model.Submission;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Submission_Roo_Configurable {
    
    declare @type: Submission: @Configurable;
    
}
